#!/usr/bin/env node

/**
 * Flutter App Build Script
 * 
 * Usage:
 *   node mobile/build-app.js <target>
 * 
 * Targets:
 *   ios       - Build iOS IPA for distribution
 *   ios:sim   - Build iOS app for simulator
 *   android   - Build Android APK
 *   macos     - Build macOS app
 *   all       - Build all targets
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const mobileDir = __dirname;
const distDir = path.join(projectRoot, 'dist');

/**
 * Check and fix Flutter platform configuration files
 * The ephemeral/Flutter-Generated.xcconfig is generated by flutter build
 */
function ensureFlutterConfig(platform) {
  const platformDir = path.join(mobileDir, platform);
  const flutterDir = path.join(platformDir, 'Flutter');
  const ephemeralDir = path.join(flutterDir, 'ephemeral');
  const generatedConfig = path.join(ephemeralDir, 'Flutter-Generated.xcconfig');
  
  // Check if Flutter-Generated.xcconfig exists
  // This file is generated during the first build, so we just need to ensure
  // flutter pub get has been run (which creates the ephemeral directory structure)
  if (!fs.existsSync(ephemeralDir)) {
    console.log(`  ⚠️  Missing ephemeral directory, running flutter pub get...`);
    execSync('flutter pub get', { cwd: mobileDir, stdio: 'inherit' });
    console.log(`  ✅ Flutter dependencies ready`);
  }
  
  // Flutter-Generated.xcconfig will be created during the build process
  // No need to check for it here
}

/**
 * Execute command with logging
 */
function exec(cmd, options = {}) {
  console.log(`  $ ${cmd}`);
  execSync(cmd, { stdio: 'inherit', ...options });
}

/**
 * Copy directory recursively using system cp command
 * This handles symlinks properly (required for macOS .app bundles)
 */
function copyDirectory(src, dest) {
  if (!fs.existsSync(src)) {
    throw new Error(`Source directory not found: ${src}`);
  }
  
  if (fs.existsSync(dest)) {
    fs.rmSync(dest, { recursive: true, force: true });
  }
  
  const destParent = path.dirname(dest);
  fs.mkdirSync(destParent, { recursive: true });
  
  // Use system cp -a to preserve symlinks (required for .app bundles)
  execSync(`cp -a "${src}" "${dest}"`, { stdio: 'inherit' });
}

/**
 * Copy files matching pattern
 */
function copyFiles(srcDir, destDir, pattern) {
  if (!fs.existsSync(srcDir)) {
    throw new Error(`Source directory not found: ${srcDir}`);
  }
  
  fs.mkdirSync(destDir, { recursive: true });
  
  const files = fs.readdirSync(srcDir);
  for (const file of files) {
    if (pattern.test(file)) {
      fs.copyFileSync(
        path.join(srcDir, file),
        path.join(destDir, file)
      );
      console.log(`  ✓ Copied ${file}`);
    }
  }
}

/**
 * Build targets
 */
const targets = {
  ios: {
    name: 'iOS (IPA)',
    build: () => {
      console.log('\n📱 Building iOS IPA...\n');
      
      ensureFlutterConfig('ios');
      exec('flutter build ipa --export-options-plist=ios/exportOptions.plist', { cwd: mobileDir });
      
      const iosDistDir = path.join(distDir, 'ios');
      const ipaSrcDir = path.join(mobileDir, 'build/ios/ipa');
      
      fs.mkdirSync(iosDistDir, { recursive: true });
      copyFiles(ipaSrcDir, iosDistDir, /\.ipa$/);
      
      // Copy manifest and other files if present
      const entries = fs.readdirSync(ipaSrcDir);
      for (const entry of entries) {
        const srcPath = path.join(ipaSrcDir, entry);
        const destPath = path.join(iosDistDir, entry);
        if (fs.statSync(srcPath).isFile()) {
          fs.copyFileSync(srcPath, destPath);
        }
      }
      
      console.log(`\n✅ iOS IPA built: ${iosDistDir}/`);
    }
  },
  
  'ios:sim': {
    name: 'iOS Simulator',
    build: () => {
      console.log('\n📱 Building iOS Simulator app...\n');
      
      ensureFlutterConfig('ios');
      exec('flutter build ios --simulator', { cwd: mobileDir });
      
      const simDistDir = path.join(distDir, 'ios-sim');
      const appSrc = path.join(mobileDir, 'build/ios/iphonesimulator/Runner.app');
      const appDest = path.join(simDistDir, 'Runner.app');
      
      copyDirectory(appSrc, appDest);
      
      console.log(`\n✅ iOS Simulator app built: ${appDest}`);
    }
  },
  
  android: {
    name: 'Android APK & AAB',
    build: () => {
      console.log('\n🤖 Building Android APK...\n');
      
      // Build APK first
      exec('flutter build apk', { cwd: mobileDir });
      
      const androidDistDir = path.join(distDir, 'android');
      const apkSrcDir = path.join(mobileDir, 'build/app/outputs/flutter-apk');
      
      copyFiles(apkSrcDir, androidDistDir, /\.apk$/);
      
      console.log('\n🤖 Building Android App Bundle (AAB)...\n');
      
      // Build AAB for Play Store
      exec('flutter build appbundle', { cwd: mobileDir });
      
      const aabSrcDir = path.join(mobileDir, 'build/app/outputs/bundle/release');
      copyFiles(aabSrcDir, androidDistDir, /\.aab$/);
      
      console.log(`\n✅ Android builds complete: ${androidDistDir}/`);
      console.log(`   • APK: for direct distribution`);
      console.log(`   • AAB: for Google Play Store`);
    }
  },
  
  macos: {
    name: 'macOS App',
    build: () => {
      console.log('\n🖥️  Building macOS app...\n');
      
      ensureFlutterConfig('macos');
      exec('flutter build macos', { cwd: mobileDir });
      
      const macosDistDir = path.join(distDir, 'macos');
      const appSrc = path.join(mobileDir, 'build/macos/Build/Products/Release/markdown_viewer_mobile.app');
      const appDest = path.join(macosDistDir, 'markdown_viewer_mobile.app');
      
      copyDirectory(appSrc, appDest);
      
      console.log(`\n✅ macOS app built: ${appDest}`);
    }
  }
};

/**
 * Main
 */
function main() {
  const args = process.argv.slice(2);
  
  if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log(`
Flutter App Build Script

Usage:
  node mobile/build-app.js <target> [target2] ...

Targets:
  ios       Build iOS IPA for distribution
  ios:sim   Build iOS app for simulator  
  android   Build Android APK & AAB (APK for direct install, AAB for Play Store)
  macos     Build macOS app
  all       Build all targets

Examples:
  node mobile/build-app.js android
  node mobile/build-app.js ios macos
  node mobile/build-app.js all
`);
    process.exit(0);
  }
  
  // Determine which targets to build
  let targetsToBuild = args;
  if (args.includes('all')) {
    targetsToBuild = Object.keys(targets);
  }
  
  // Validate targets
  for (const target of targetsToBuild) {
    if (!targets[target]) {
      console.error(`❌ Unknown target: ${target}`);
      console.error(`   Available targets: ${Object.keys(targets).join(', ')}, all`);
      process.exit(1);
    }
  }
  
  console.log('🚀 Flutter App Build');
  console.log(`   Targets: ${targetsToBuild.map(t => targets[t].name).join(', ')}`);
  
  // Ensure dist directory exists
  fs.mkdirSync(distDir, { recursive: true });
  
  // Build each target
  const results = [];
  for (const target of targetsToBuild) {
    try {
      targets[target].build();
      results.push({ target, success: true });
    } catch (error) {
      console.error(`\n❌ Failed to build ${targets[target].name}:`, error.message);
      results.push({ target, success: false, error: error.message });
    }
  }
  
  // Summary
  console.log('\n' + '='.repeat(50));
  console.log('Build Summary:');
  for (const { target, success, error } of results) {
    const icon = success ? '✅' : '❌';
    const status = success ? 'Success' : `Failed: ${error}`;
    console.log(`  ${icon} ${targets[target].name}: ${status}`);
  }
  
  const failed = results.filter(r => !r.success);
  if (failed.length > 0) {
    process.exit(1);
  }
}

main();
